name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip nodejs jupyterlab=3 jupyter-packaging cookiecutter

    - name: Create theme extension
      shell: bash -l {0}
      run: |
        cookiecutter . --no-input
        cd mytheme
        pip install -e .
        jlpm run eslint:check
        jupyter labextension list 1>labextensions 2>&1
        cat labextensions | grep "mytheme.*OK"
        python -m jupyterlab.browser_check
        jlpm run install:extension
        jupyter labextension build .
        jupyter labextension uninstall mytheme
        pip uninstall -y mytheme jupyterlab
